quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/prenotazioneappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

quarkus.rest-client.utente-client.url=http://localhost:9090/auth
quarkus.rest-client.utente-client.username=root
quarkus.rest-client.utente-client.password=password


kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.my-channel.connector=smallrye-kafka
mp.messaging.outgoing.my-channel.topic=notification
mp.messaging.outgoing.my-channel.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer