quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USERNAME:root}
quarkus.datasource.password=${DB_PASSWORD:rootpassword}
quarkus.datasource.reactive.url=${DB_URL:mysql://localhost:3306/prenotazioneappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}

# Configurazione esclusiva dei test
%test.quarkus.datasource.db-kind=mysql
%test.quarkus.datasource.username=root
%test.quarkus.datasource.password=rootpassword
%test.quarkus.datasource.reactive.url=mysql://localhost:3306/prenotazionetest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC


# REST Client UserService
quarkus.rest-client.utente-client.url=${USER_SERVICE_URL:http://localhost:9090/auth}
quarkus.rest-client.utente-client.username=root
quarkus.rest-client.utente-client.password=password


# Kafka
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

mp.messaging.outgoing.my-channel.connector=smallrye-kafka
mp.messaging.outgoing.my-channel.topic=notification
mp.messaging.outgoing.my-channel.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer


# JWT
quarkus.security.jwt.token.secret-key=5367566859703373367639792F423F452848284D6251655468576D5A71347437


# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200